global using MembershipSystem;
global using MembershipSystem.Template.Models;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Razor.TagHelpers;
global using Microsoft.EntityFrameworkCore;
global using System.Diagnostics;
global using System.Text;
