global using MembershipSystem;
global using MembershipSystem.Decorator.Models;
global using MembershipSystem.Decorator.Repositories;
global using MembershipSystem.Decorator.Repositories.Decorators;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Caching.Memory;